# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

group = DefineGroup('POSIX', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
