#-*- encoding: utf-8 -*-
#-------------------------------------------------------------------------------
# SConscript
# Copyright (c) Shanghai Real-Thread Electronic Technology Co., Ltd.
#-------------------------------------------------------------------------------
import os
from building import *
Import('RTT_ROOT')
Import('rtconfig')

#-------------------------------------------------------------------------------
# Package configuration
#-------------------------------------------------------------------------------
PKGNAME = 'CanFestival'
DEPENDS = ['COMP_USING_CANFESTIVAL']

#-------------------------------------------------------------------------------
# Compile the configuration
#-------------------------------------------------------------------------------
SOURCES          = Glob('src/*.c')

LOCAL_CPPPATH    = []
LOCAL_CCFLAGS    = ""
LOCAL_ASFLAGS    = ""

CPPPATH          = [os.path.join(GetCurrentDir(), 'inc')]

CCFLAGS          = ""
ASFLAGS          = ""

CPPDEFINES       = []
LOCAL_CPPDEFINES = []

LIBS             = []
LIBPATH          = [GetCurrentDir()]

LINKFLAGS        = ""

#-------------------------------------------------------------------------------
# Feature clip configuration, optional
#-------------------------------------------------------------------------------
SrcRemove(SOURCES, 'src/dcf.c')
SrcRemove(SOURCES, 'src/lss.c')
SrcRemove(SOURCES, 'src/symbols.c')

#-------------------------------------------------------------------------------
# Compiler platform configuration, optional
#-------------------------------------------------------------------------------

#-------------------------------------------------------------------------------
# System variables
#-------------------------------------------------------------------------------
objs   = []
root   = GetCurrentDir()

#-------------------------------------------------------------------------------
# Sub target
#-------------------------------------------------------------------------------
list = os.listdir(root)
if GetDepend(DEPENDS):
    for d in list:
        path = os.path.join(root, d)
        if os.path.isfile(os.path.join(path, 'SConscript')):
            objs = objs + SConscript(os.path.join(d, 'SConscript'))

#-------------------------------------------------------------------------------
# Main target
#-------------------------------------------------------------------------------
objs += DefineGroup(name = PKGNAME, src = SOURCES, depend = DEPENDS,
                    CPPPATH          = CPPPATH,
                    CCFLAGS          = CCFLAGS,
                    ASFLAGS          = ASFLAGS,
                    LOCAL_CPPPATH    = LOCAL_CPPPATH,
                    LOCAL_CCFLAGS    = LOCAL_CCFLAGS,
                    LOCAL_ASFLAGS    = LOCAL_ASFLAGS,
                    CPPDEFINES       = CPPDEFINES,
                    LOCAL_CPPDEFINES = LOCAL_CPPDEFINES,
                    LIBS             = LIBS,
                    LIBPATH          = LIBPATH,
                    LINKFLAGS        = LINKFLAGS)

Return("objs")
#-------------------------------------------------------------------------------
# End
#-------------------------------------------------------------------------------
