board:
  buy_url_cn: N/A
  buy_url_global: N/A
  debug_interface: SWD
  debugger: OpenOCD
  description_en: N/A
  description_zh: 睿擎3562是睿擎平台官方推荐的评估板，专为工业场景设计，内嵌RT-Thread睿擎工业开发平台，同时集成了丰富的硬件接口和扩展能力，助力开发者快速验证和开发工业应用。该评估板基于高性能的RK3562芯片，支持双千兆以太网、PCIE、多种显示接口以及丰富的工业通信接口，同时具备灵活的扩展性，可轻松连接各类外设，满足多样化的工业开发需求。
  emulator_machine: ''
  large_image: documents/images/large_image.png
  name: RC-Pi-3562
  price_cn: N/A CNY
  price_global: N/A USD
  sale_contact_cn: N/A
  sale_contact_global: N/A
  small_image: documents/images/small_image.png
  vendor: Real-Thread
  version: V1.0
chip:
  chip_name: RK3562J
  clock_source: N/A
  device_vendor: RockChip
  family_name: RK3562
  rx_name: N/A
  series_name: RK3562
  source_freq: N/A
  sub_series_name: RK3562
  target_freq: N/A
  tx_name: N/A
  uart_name: UART1
docs: []
example_projects:
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_backtrace
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_backtrace
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_ipc_event
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_ipc_event
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_ipc_mailbox
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_ipc_mailbox
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_ipc_msg
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_ipc_msg
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_ipc_mutex
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_ipc_mutex
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_ipc_sem
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_ipc_sem
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_msh
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_msh
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 01_os_thread
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 01_os_thread
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 02_peripheral_can_send
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 02_peripheral_can_send
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 02_peripheral_i2c_hym8563
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 02_peripheral_i2c_hym8563
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 02_peripheral_pwm
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 02_peripheral_pwm
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 02_peripheral_pwm_capture
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 02_peripheral_pwm_capture
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 02_peripheral_spi_norflash
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 02_peripheral_spi_norflash
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 02_peripheral_wdg
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 02_peripheral_wdg
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 06_bus_ethercat_master_csp
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 06_bus_ethercat_master_csp
  project_type: bare-metal|@notUsed|@notUsed
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 08_misc_amp_factory_default
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 08_misc_amp_factory_default
  project_type: bare-metal|@notUsed|@notUsed
features:
- High-Performance Computing Core: Quad-core ARM Cortex-A53 processor with a maximum
    frequency of up to 2.0GHz, providing strong computing power support for industrial
    scenarios​
- Professional Graphics and AI Acceleration: Equipped with ARM G52 2EE GPU, fully
    supporting graphics interfaces including OpenGL ES 1.1/2.0/3.2, OpenCL 2.0, and
    Vulkan 1.1; built-in 1TOPS neural network acceleration engine, compatible with
    multiple operation formats such as INT8/INT16/FP16/BF16/TF32, meeting the needs
    of AI inference and graphics processing​
- High-Speed Industrial-Grade Network: Equipped with dual 1000Mbps Ethernet interfaces
    (RGMII + PCIe), easily coping with high-speed data transmission scenarios and
    ensuring the stability of industrial communication​
- Large-Capacity and Flexible Storage: Maximum support for 8GB LPDDR4/LPDDR4x memory,
    providing sufficient operating space; covering storage solutions including eMMC,
    M.2 NVMe SSD high-speed storage and microSD expansion, meeting different data
    storage needs​
- HD Display and Acquisition: Supports HD display interfaces including MIPI DSI (2048x1080@60fps)
    and LVDS (1280x800@60fps); multiple MIPI CSI camera interfaces, enabling efficient
    video acquisition and image processing​
- Full-Scenario Wireless Expansion: Integrates dual-band 2.4G/5.8G WiFi and BT5.0,
    providing stable wireless connection; equipped with Mini PCIe expansion interface,
    supporting the access of 4G/5G LTE communication modules to expand wide-area communication
    capabilities
features_zh:
- 高性能运算核心: 四核 ARM Cortex-A53 处理器，最高主频达 2.0GHz，为工业场景提供强劲算力支撑​
- 专业图形与 AI 加速: 搭载 ARM G52 2EE GPU，全面支持 OpenGL ES 1.1/2.0/3.2、OpenCL 2.0、Vulkan 1.1
    图形接口；内置 1TOPS 神经网络加速引擎，兼容 INT8/INT16/FP16/BF16/TF32 多种运算格式，满足 AI 推理与图形处理需求​
- 高速工业级网络: 配备双千兆以太网接口（RGMII+PCIe），轻松应对高速数据传输场景，保障工业通信稳定性​
- 大容量灵活存储: 最大支持 8GB LPDDR4/LPDDR4x 内存，提供充足运行空间；涵盖 eMMC、M.2 NVMe SSD 高速存储及 microSD
    扩展方案，满足不同数据存储需求​
- 高清显示与采集: 支持 MIPI DSI（2048x1080@60fps）、LVDS（1280x800@60fps）高清显示接口；多路 MIPI CSI 摄像头接口，可高效实现视频采集与图像处理​
- 全场景无线扩展: 集成双频 2.4G/5.8G WiFi 与 BT5.0，提供稳定无线连接；配备 Mini PCIe 扩展接口，支持 4G/5G LTE 通信模块接入，拓展广域通信能力
pkg_type: Board_Support_Packages
pkg_vendor: Real-Thread
pkg_version: 1.1.0
template_projects:
- builtin_files:
  - files_and_folders:
    - .settings
    - applications
    - board
    - packages
    - .config
    - .cproject
    - .project
    - Kconfig
    - rtconfig.h
    - rtconfig.py
    - SConscript
    - SConstruct
    source_path_offset: 00_amp_helloworld
    target_path_offset: ''
  - files_and_folders:
    - rt-thread
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - platform
    source_path_offset: .
    target_path_offset: ''
  - files_and_folders:
    - rk3562.svd
    source_path_offset: debug/svd/
    target_path_offset: .settings
  external_files: []
  project_description: ''
  project_name: 00_amp_helloworld
  project_type: bare-metal|@notUsed|@notUsed
yaml_version: 3
