from building import *
import rtconfig
import os

src = []
inc = []
group = []
LOCAL_CFLAGS = ""

cwd = GetCurrentDir() # get current dir path

port_src = Glob('*.c')
port_inc = [cwd]
group = group + DefineGroup('LVGL-port', port_src, depend = ['COMP_USING_LVGL'], CPPPATH = port_inc)

# check if .h or .hpp files exists
def check_h_hpp_exists(path):
    file_dirs = os.listdir(path)
    for file_dir in file_dirs:
        if os.path.splitext(file_dir)[1] in ['.h', '.hpp']:
            return True
    return False

lvgl_src_cwd = '../src/'
inc += [os.path.join(GetCurrentDir(), lvgl_src_cwd)]
src += Glob(os.path.join(lvgl_src_cwd, '*.c'))

for root, dirs, files in os.walk(os.path.join(GetCurrentDir(), lvgl_src_cwd)):
    for dir in dirs:
        current_path = os.path.join(root, dir)
        src += Glob(os.path.join(os.path.relpath(current_path, cwd),'*.c'))

group = group + DefineGroup('lvgl', src, depend = ['COMP_USING_LVGL'], CPPPATH = inc, LOCAL_CFLAGS = LOCAL_CFLAGS)

list = os.listdir(cwd)
for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        group = group + SConscript(os.path.join(d, 'SConscript'))

Return('group')
