from building import *
Import('rtconfig')

src = []
cwd = GetCurrentDir()
group   = []
CPPPATH = [cwd]

if rtconfig.PLATFORM in ['gcc']:
    group = DefineGroup('POSIX', src, depend = ['RT_USING_MODULE'], CPPPATH = CPPPATH)

Return('group')
